services:
  montechelo:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    command: /start
    image: montechelo_django
    container_name: montechelo_django
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
      - celery_beat
      - celery_worker
      - flower

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_ENTRY_PORT}:${REDIS_OUTPUT_PORT}"

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: montechelo_django_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: montechelo_django_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: montechelo_django_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "${FLOWER_ENTRY_PORT}:${FLOWER_OUTPUT_PORT}"
    depends_on:
      - redis
