# Generated by Django 4.2.18 on 2025-01-28 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Create by')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Update by')),
                ('title', models.CharField(help_text='El título debe ser único.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de la tarea.')),
                ('is_completed', models.BooleanField(default=False, help_text='Estado de la tarea, completada o no.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la tarea.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización de la tarea.')),
                ('user', models.ForeignKey(help_text='El usuario dueño de la tarea.', on_delete=django.db.models.deletion.CASCADE, related_name='to_dos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'user')},
            },
        ),
    ]
